version: '3'

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

services:
  devi.tools:
    image: webdevops/nginx
    container_name: devi.tools
    restart: always
    networks:
      - reverse-proxy
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - WEB_DOCUMENT_INDEX=index.html
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
