name: deploy

on: push

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "ci@devi.tools"

      - name: Configure SSH Key
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "${{ secrets.DEPLOY_SERVER_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      # example DEPLOY_HOST_PRD: devi.tools
      - name: Configure SSH known hosts
        run: |
          echo -e "${{ secrets.DEPLOY_HOST_PRD }}" > ~/.ssh/known_hosts
          echo "chmod on ~/.ssh/known_hosts"
          chmod 644 ~/.ssh/known_hosts

      # example DEPLOY_REMOTE_PRD: ssh://heimdall@devi.tools:/projects/devi.tools/repo
      - name: Deploy to production
        run: |
          rm -rf .git
          cp .environment/devi.tools/.env .env
          cp .environment/devi.tools/docker-compose.yml docker-compose.yml
          rm -rf public
          mv dist public
          git init
          git add .
          git commit --quiet -m "[deploy] $(date)"
          git remote add production ${{ secrets.DEPLOY_REMOTE_PRD }}
          git push production master --force
          